version: '3'

services:
  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=abcdef
    ports:
      - "5432:5432"

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=scope
      - KEYCLOAK_PASSWORD=scope
      - KEYCLOAK_IMPORT=/tmp/keycloak_scope.json
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_USER=keycloak
      - DB_PASSWORD=abcdef
    volumes:
      - ./keycloak_scope.json:/tmp/keycloak_scope.json
    ports:
      - "8080:8080"
