version: '3'

services:
    scope:
        restart: always
        build: .
        expose:
            - 55850
            - 55851
            - 55852
            - 55853
        volumes:
            - ${SCOPE_DATA_DIR:-./scope_data/}:/root/.local/share/SCope/
            - app-volume:/app
        entrypoint: ['bash /app/start.sh']
    httpd:
        restart: always
        build: ./apache
        ports:
            - ${SCOPE_PORT:-80}:80
        depends_on:
            - scope
        volumes:
            - app-volume:/usr/local/apache2/htdocs/

volumes:
    app-volume:
