version: '3'

services:
    scope:
        restart: always
        build: .
        expose:
            - 55850
            - 55851
            - 55852
            - 55853
        volumes:
            - ${SCOPE_DATA_DIR:-./scope_data/}:/root/.local/share/SCope/
        entrypoint: ["poetry", "run", "hypercorn", "--bind", "0.0.0.0", "main:scope_api"]
    httpd:
        restart: always
        build: ./apache
        ports:
            - ${SCOPE_PORT:-80}:80
        depends_on:
            - scope
        volumes:
            - ./:/usr/local/apache2/htdocs/
