# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from scopeserver.modules.gserver import s_pb2 as s__pb2


class MainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCellColorByFeatures = channel.unary_unary(
        '/scope.Main/getCellColorByFeatures',
        request_serializer=s__pb2.CellColorByFeaturesRequest.SerializeToString,
        response_deserializer=s__pb2.CellColorByFeaturesReply.FromString,
        )
    self.getFeatures = channel.unary_unary(
        '/scope.Main/getFeatures',
        request_serializer=s__pb2.FeatureRequest.SerializeToString,
        response_deserializer=s__pb2.FeatureReply.FromString,
        )
    self.getCoordinates = channel.unary_unary(
        '/scope.Main/getCoordinates',
        request_serializer=s__pb2.CoordinateRequest.SerializeToString,
        response_deserializer=s__pb2.CoordinateReply.FromString,
        )
    self.getMyLooms = channel.unary_unary(
        '/scope.Main/getMyLooms',
        request_serializer=s__pb2.MyLoomListRequest.SerializeToString,
        response_deserializer=s__pb2.MyLoomListReply.FromString,
        )


class MainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCellColorByFeatures(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getFeatures(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getCoordinates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMyLooms(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCellColorByFeatures': grpc.unary_unary_rpc_method_handler(
          servicer.getCellColorByFeatures,
          request_deserializer=s__pb2.CellColorByFeaturesRequest.FromString,
          response_serializer=s__pb2.CellColorByFeaturesReply.SerializeToString,
      ),
      'getFeatures': grpc.unary_unary_rpc_method_handler(
          servicer.getFeatures,
          request_deserializer=s__pb2.FeatureRequest.FromString,
          response_serializer=s__pb2.FeatureReply.SerializeToString,
      ),
      'getCoordinates': grpc.unary_unary_rpc_method_handler(
          servicer.getCoordinates,
          request_deserializer=s__pb2.CoordinateRequest.FromString,
          response_serializer=s__pb2.CoordinateReply.SerializeToString,
      ),
      'getMyLooms': grpc.unary_unary_rpc_method_handler(
          servicer.getMyLooms,
          request_deserializer=s__pb2.MyLoomListRequest.FromString,
          response_serializer=s__pb2.MyLoomListReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'scope.Main', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
