# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SCope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SCope.proto',
  package='scope',
  syntax='proto3',
  serialized_pb=_b('\n\x0bSCope.proto\x12\x05scope\"L\n\x1a\x43\x65llColorByFeaturesRequest\x12\x0b\n\x03lfp\x18\x01 \x01(\t\x12\t\n\x01\x65\x18\x02 \x03(\t\x12\t\n\x01\x66\x18\x03 \x03(\t\x12\x0b\n\x03lte\x18\x04 \x01(\x08\"%\n\x18\x43\x65llColorByFeaturesReply\x12\t\n\x01v\x18\x01 \x03(\t\"(\n\x0e\x46\x65\x61tureRequest\x12\x0b\n\x03lfp\x18\x01 \x01(\t\x12\t\n\x01q\x18\x02 \x01(\t\"\x19\n\x0c\x46\x65\x61tureReply\x12\t\n\x01v\x18\x01 \x03(\t2\xa4\x01\n\x05SCope\x12^\n\x16getCellColorByFeatures\x12!.scope.CellColorByFeaturesRequest\x1a\x1f.scope.CellColorByFeaturesReply\"\x00\x12;\n\x0bgetFeatures\x12\x15.scope.FeatureRequest\x1a\x13.scope.FeatureReply\"\x00\x62\x06proto3')
)




_CELLCOLORBYFEATURESREQUEST = _descriptor.Descriptor(
  name='CellColorByFeaturesRequest',
  full_name='scope.CellColorByFeaturesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lfp', full_name='scope.CellColorByFeaturesRequest.lfp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='e', full_name='scope.CellColorByFeaturesRequest.e', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f', full_name='scope.CellColorByFeaturesRequest.f', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lte', full_name='scope.CellColorByFeaturesRequest.lte', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=98,
)


_CELLCOLORBYFEATURESREPLY = _descriptor.Descriptor(
  name='CellColorByFeaturesReply',
  full_name='scope.CellColorByFeaturesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='scope.CellColorByFeaturesReply.v', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=137,
)


_FEATUREREQUEST = _descriptor.Descriptor(
  name='FeatureRequest',
  full_name='scope.FeatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lfp', full_name='scope.FeatureRequest.lfp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q', full_name='scope.FeatureRequest.q', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=179,
)


_FEATUREREPLY = _descriptor.Descriptor(
  name='FeatureReply',
  full_name='scope.FeatureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='scope.FeatureReply.v', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['CellColorByFeaturesRequest'] = _CELLCOLORBYFEATURESREQUEST
DESCRIPTOR.message_types_by_name['CellColorByFeaturesReply'] = _CELLCOLORBYFEATURESREPLY
DESCRIPTOR.message_types_by_name['FeatureRequest'] = _FEATUREREQUEST
DESCRIPTOR.message_types_by_name['FeatureReply'] = _FEATUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CellColorByFeaturesRequest = _reflection.GeneratedProtocolMessageType('CellColorByFeaturesRequest', (_message.Message,), dict(
  DESCRIPTOR = _CELLCOLORBYFEATURESREQUEST,
  __module__ = 'SCope_pb2'
  # @@protoc_insertion_point(class_scope:scope.CellColorByFeaturesRequest)
  ))
_sym_db.RegisterMessage(CellColorByFeaturesRequest)

CellColorByFeaturesReply = _reflection.GeneratedProtocolMessageType('CellColorByFeaturesReply', (_message.Message,), dict(
  DESCRIPTOR = _CELLCOLORBYFEATURESREPLY,
  __module__ = 'SCope_pb2'
  # @@protoc_insertion_point(class_scope:scope.CellColorByFeaturesReply)
  ))
_sym_db.RegisterMessage(CellColorByFeaturesReply)

FeatureRequest = _reflection.GeneratedProtocolMessageType('FeatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREREQUEST,
  __module__ = 'SCope_pb2'
  # @@protoc_insertion_point(class_scope:scope.FeatureRequest)
  ))
_sym_db.RegisterMessage(FeatureRequest)

FeatureReply = _reflection.GeneratedProtocolMessageType('FeatureReply', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREREPLY,
  __module__ = 'SCope_pb2'
  # @@protoc_insertion_point(class_scope:scope.FeatureReply)
  ))
_sym_db.RegisterMessage(FeatureReply)



_SCOPE = _descriptor.ServiceDescriptor(
  name='SCope',
  full_name='scope.SCope',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=209,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCellColorByFeatures',
    full_name='scope.SCope.getCellColorByFeatures',
    index=0,
    containing_service=None,
    input_type=_CELLCOLORBYFEATURESREQUEST,
    output_type=_CELLCOLORBYFEATURESREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getFeatures',
    full_name='scope.SCope.getFeatures',
    index=1,
    containing_service=None,
    input_type=_FEATUREREQUEST,
    output_type=_FEATUREREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCOPE)

DESCRIPTOR.services_by_name['SCope'] = _SCOPE

# @@protoc_insertion_point(module_scope)
