export const SET_APP_LOADING = 'SET_APP_LOADING';

export const SET_UUID = 'SET_UUID';

export const SET_SESSION_MODE = 'SET_SESSION_MODE';

export const TOGGLE_SIDEBAR_VISIBLE = 'TOGGLE_SIDEBAR_VISIBLE';
