"""Data serialisation test

Revision ID: 78e110998229
Revises: 9757dac77d81
Create Date: 2022-03-22 14:53:44.618290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78e110998229"
down_revision = "9757dac77d81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matrices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("row", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("matrices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_matrices_id"), ["id"], unique=False)

    op.create_table(
        "binary_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset", sa.Integer(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("data_format", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("binary_data", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_binary_data_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("binary_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_binary_data_id"))

    op.drop_table("binary_data")
    with op.batch_alter_table("matrices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matrices_id"))

    op.drop_table("matrices")
    # ### end Alembic commands ###
