"""add_has_password_to_user

Revision ID: 752c56a2f7bb
Revises: ad040c6c31d3
Create Date: 2025-11-29 19:30:00.827699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752c56a2f7bb'
down_revision: Union[str, None] = 'ad040c6c31d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_password', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET has_password = true")
    op.alter_column('users', 'has_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_password')
    # ### end Alembic commands ###
