"""Add file_size and converted_size to datasets

Revision ID: fc5564e2375d
Revises: 752c56a2f7bb
Create Date: 2025-12-02 11:53:59.584017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5564e2375d'
down_revision: Union[str, None] = '752c56a2f7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('converted_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'converted_size')
    op.drop_column('datasets', 'file_size')
    # ### end Alembic commands ###
