name: Client CI
on:
  push:

  pull_request:
    paths-ignore:
    - 'src/**'

jobs:
  client-quality-checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run check-style
      - run: npm run lint
      - run: npm test
      
