name: Security Audit

on:
  pull_request: {}

jobs:
  semgrep:
    name: Scan with SemGrep
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2

      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/gitlab-bandit
            p/security-audit
            p/secrets
            p/sql-injection
            p/xss
            p/javascript
            p/typescript
          generateSarif: "1"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
